# Site settings
title: kwakblog
email: sk@stephaniekwak.com
description: > # this means to ignore newlines until "baseurl:"
  a tech/code blog because why not
# baseurl: "/kwakblog"
url: "http://www.stephaniekwak.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
