# Site settings
title: kwakblog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  a tech/code blog by stephanie kwak
# baseurl: "/kwakblog"
url: "http://www.stephaniekwak.com" # the base hostname & protocol for your site
twitter_username: kwakstop
github_username: skwak

# Build settings
markdown: kramdown
